#!/usr/bin/env node
// Regenerates character-images.generated.js from the .jpg portraits in this
// folder.
//
// Why this exists: "Download PNG" uses html-to-image, which needs to
// fetch() each image to inline it into the exported canvas. Chrome refuses
// fetch() between two file:// resources ("Access to fetch at '...' from
// origin 'null' has been blocked by CORS policy"), so opening baseline.html
// directly and downloading a card silently exports without the portrait.
// Embedding each portrait as a data URI up front sidesteps the network
// request entirely — there's nothing left to fetch.
//
// Run: node complete-version/classes/class_cards/build-images.js
// (re-run whenever a portrait file is added or replaced)

const fs = require('fs');
const path = require('path');

const DIR = __dirname;
const MIME = { jpg: 'jpeg', jpeg: 'jpeg', png: 'png' };

const files = fs.readdirSync(DIR)
  .filter(f => /\.(jpe?g|png)$/i.test(f))
  .sort();

const entries = files.map(file => {
  const ext = path.extname(file).slice(1).toLowerCase();
  const base64 = fs.readFileSync(path.join(DIR, file)).toString('base64');
  return `  ${JSON.stringify(file)}: "data:image/${MIME[ext]};base64,${base64}"`;
}).join(',\n');

const output = `// AUTO-GENERATED by build-images.js from the .jpg files in this folder —
// do not edit directly. Regenerate with:
//   node complete-version/classes/class_cards/build-images.js
//
// Maps each portrait filename to an inlined data URI. baseline.html uses
// this instead of the bare filename so "Download PNG" (html-to-image) has
// nothing left to fetch().
const CHARACTER_IMAGES = {
${entries}
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { CHARACTER_IMAGES };
}
`;

fs.writeFileSync(path.join(DIR, 'character-images.generated.js'), output);
console.log(`character-images.generated.js regenerated (${files.length} portraits inlined)`);
